[TP2-6] - create PUT query for user
StayTeeVone/pepper-team-back pull request #1
Opened 2023-02-18 20:25 UTC by Shapovall

Was created PUT query.

2023-02-18 20:26 UTC, StayTeeVone approved these changes
Good.

2023-02-18 20:28 UTC, GOSTT22 approved these changes
Well done

2023-02-18 20:30 UTC, OleynikBogdan approved these changes

2023-02-18 21:04 UTC, buba3230 requested changes

2023-02-18 21:04 UTC, buba3230 commented on routes/users.js
> +      res.send({data: `User with ${id} was updated to email: ${email}, name: ${name}, phone: ${phone}`});
You should return user object... New user

2023-02-20 16:42 UTC, buba3230 approved these changes

2023-02-20 16:42 UTC, buba3230 approved these changes

2023-02-20 16:43 UTC, buba3230 approved these changes

2023-02-23 14:43 UTC, buba3230 approved these changes

2023-02-23 14:44 UTC, buba3230 approved these changes

2023-02-23 14:48 UTC, OleynikBogdan approved these changes

2023-02-23 17:45 UTC, StayTeeVone approved these changes

2023-02-23 17:47 UTC, merged